# Workflow based on the w3c/spec-prod action example to deploy to GitHub Pages:
# https://github.com/w3c/spec-prod/blob/main/docs/examples.md#deploy-to-github-pages

name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
